/**
 * officeRegistry.ts — Office Registry data-access layer
 *
 * This Vite SPA has no backend API routes, so this module IS the API layer.
 * It maps the spec's REST endpoints to Supabase queries:
 *
 *   P2-T1  GET    /api/offices                  → listOffices()
 *   P2-T2  POST   /api/offices                  → createOffice()
 *   P2-T3  GET    /api/offices/[id]             → getOffice()
 *   P2-T4  PUT    /api/offices/[id]             → updateOffice()
 *   P2-T5  DELETE /api/offices/[id]             → deactivateOffice()
 *   P2-T6  POST   /api/offices/bulk-import       → bulkImportOffices()
 *   P2-T7  PUT    /api/offices/street-mapping    → mapStreetsToOffice()
 *   P2-T8  GET    /api/offices/hierarchy/[id]    → getChildOffices()
 *   P2-T9/T10/T11 assignment logic               → assignOfficeForAddress()
 *
 * Permissions are enforced by Supabase RLS (admin-only writes).
 */
import { supabase } from "@/lib/supabase";

export type OfficeType = "regional" | "district" | "ward" | "mtaa" | "department";

export interface Office {
  id: string;
  office_code: string;
  name: string;
  name_sw?: string | null;
  name_en?: string | null;
  office_type: OfficeType;
  parent_id?: string | null;
  region?: string | null;
  district?: string | null;
  ward?: string | null;
  mtaa?: string | null;
  department_type?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  head_officer_id?: string | null;
  head_officer_name?: string | null;
  served_streets?: string[];
  active: boolean;
  created_at?: string;
  updated_at?: string;
  created_by?: string | null;
}

export interface OfficeFilters {
  office_type?: OfficeType;
  region?: string;
  district?: string;
  ward?: string;
  parent_id?: string;
  active?: boolean;
  search?: string;
}

const TABLE = "office_registry";

// ── P2-T1: List offices with filters ──────────────────────────────────────────
export async function listOffices(filters: OfficeFilters = {}): Promise<Office[]> {
  let q = supabase.from(TABLE).select("*").order("office_type").order("name");

  if (filters.office_type) q = q.eq("office_type", filters.office_type);
  if (filters.region) q = q.eq("region", filters.region);
  if (filters.district) q = q.eq("district", filters.district);
  if (filters.ward) q = q.eq("ward", filters.ward);
  if (filters.parent_id) q = q.eq("parent_id", filters.parent_id);
  if (typeof filters.active === "boolean") q = q.eq("active", filters.active);
  if (filters.search) {
    q = q.or(
      `name.ilike.%${filters.search}%,office_code.ilike.%${filters.search}%,mtaa.ilike.%${filters.search}%`,
    );
  }

  const { data, error } = await q;
  if (error) throw error;
  return (data || []) as Office[];
}

// ── P2-T3: Get one office ──────────────────────────────────────────────────────
export async function getOffice(id: string): Promise<Office | null> {
  const { data, error } = await supabase.from(TABLE).select("*").eq("id", id).maybeSingle();
  if (error) throw error;
  return data as Office | null;
}

// ── P2-T2: Create office (office_code auto-generated by DB trigger) ───────────
export async function createOffice(
  office: Omit<Office, "id" | "office_code" | "created_at" | "updated_at" | "active"> & {
    active?: boolean;
    office_code?: string;
  },
): Promise<Office> {
  const payload = { ...office, active: office.active ?? true };
  // Let DB trigger generate office_code if not supplied
  if (!payload.office_code) delete (payload as Record<string, unknown>).office_code;
  const { data, error } = await supabase.from(TABLE).insert(payload).select().single();
  if (error) throw error;
  return data as Office;
}

// ── P2-T4: Update office ───────────────────────────────────────────────────────
export async function updateOffice(id: string, updates: Partial<Office>): Promise<Office> {
  // Don't allow office_code overwrite via update unless explicitly intended
  const { data, error } = await supabase.from(TABLE).update(updates).eq("id", id).select().single();
  if (error) throw error;
  return data as Office;
}

// ── P2-T5: Deactivate office (soft delete) ─────────────────────────────────────
export async function deactivateOffice(id: string): Promise<void> {
  const { error } = await supabase.from(TABLE).update({ active: false }).eq("id", id);
  if (error) throw error;
}

export async function reactivateOffice(id: string): Promise<void> {
  const { error } = await supabase.from(TABLE).update({ active: true }).eq("id", id);
  if (error) throw error;
}

// ── P2-T7: Map streets to a mtaa office ────────────────────────────────────────
export async function mapStreetsToOffice(officeId: string, streets: string[]): Promise<Office> {
  const clean = Array.from(new Set(streets.map((s) => s.trim()).filter(Boolean)));
  const { data, error } = await supabase
    .from(TABLE)
    .update({ served_streets: clean })
    .eq("id", officeId)
    .select()
    .single();
  if (error) throw error;
  return data as Office;
}

// ── P2-T8: Get child offices in the hierarchy ──────────────────────────────────
export async function getChildOffices(parentId: string): Promise<Office[]> {
  const { data, error } = await supabase
    .from(TABLE)
    .select("*")
    .eq("parent_id", parentId)
    .order("office_type")
    .order("name");
  if (error) throw error;
  return (data || []) as Office[];
}

// Build a full hierarchy tree from a flat list
export interface OfficeNode extends Office {
  children: OfficeNode[];
}
export function buildHierarchyTree(offices: Office[]): OfficeNode[] {
  const map = new Map<string, OfficeNode>();
  const roots: OfficeNode[] = [];
  offices.forEach((o) => map.set(o.id, { ...o, children: [] }));
  offices.forEach((o) => {
    const node = map.get(o.id)!;
    if (o.parent_id && map.has(o.parent_id)) {
      map.get(o.parent_id)!.children.push(node);
    } else {
      roots.push(node);
    }
  });
  return roots;
}

// ── P2-T6: Bulk CSV import ─────────────────────────────────────────────────────
// CSV columns: office_type,name,name_sw,region,district,ward,mtaa,department_type,phone,email,address
export interface BulkImportRow {
  office_type: string;
  name: string;
  name_sw?: string;
  name_en?: string;
  region?: string;
  district?: string;
  ward?: string;
  mtaa?: string;
  department_type?: string;
  phone?: string;
  email?: string;
  address?: string;
}
export interface BulkImportResult {
  inserted: number;
  failed: number;
  errors: { row: number; reason: string }[];
}

export function parseOfficeCSV(csv: string): BulkImportRow[] {
  const lines = csv
    .trim()
    .split(/\r?\n/)
    .filter((l) => l.trim());
  if (lines.length < 2) return [];
  const headers = lines[0].split(",").map((h) => h.trim().toLowerCase());
  return lines.slice(1).map((line) => {
    // Simple CSV split (handles quoted fields)
    const cells: string[] = [];
    let cur = "",
      inQ = false;
    for (const ch of line) {
      if (ch === '"') inQ = !inQ;
      else if (ch === "," && !inQ) {
        cells.push(cur);
        cur = "";
      } else cur += ch;
    }
    cells.push(cur);
    const row: Record<string, string> = {};
    headers.forEach((h, i) => {
      row[h] = (cells[i] || "").trim();
    });
    return row as unknown as BulkImportRow;
  });
}

export async function bulkImportOffices(rows: BulkImportRow[]): Promise<BulkImportResult> {
  const result: BulkImportResult = { inserted: 0, failed: 0, errors: [] };
  const validTypes = ["regional", "district", "ward", "mtaa", "department"];

  for (let i = 0; i < rows.length; i++) {
    const r = rows[i];
    if (!r.name || !validTypes.includes(r.office_type)) {
      result.failed++;
      result.errors.push({
        row: i + 2,
        reason: !r.name ? "Missing name" : `Invalid office_type: ${r.office_type}`,
      });
      continue;
    }
    try {
      await createOffice({
        name: r.name,
        name_sw: r.name_sw || r.name,
        name_en: r.name_en || r.name,
        office_type: r.office_type as OfficeType,
        region: r.region || null,
        district: r.district || null,
        ward: r.ward || null,
        mtaa: r.mtaa || null,
        department_type: r.department_type || null,
        phone: r.phone || null,
        email: r.email || null,
        address: r.address || null,
      });
      result.inserted++;
    } catch (e) {
      result.failed++;
      result.errors.push({ row: i + 2, reason: (e as Error).message });
    }
  }
  return result;
}

// ── P2-T9 / T10 / T11: Citizen office assignment ───────────────────────────────
/**
 * Find the correct office for a given address using the DB lookup function.
 * Falls back through mtaa → ward → district → regional.
 */
export async function findOfficeForAddress(
  region: string,
  district: string,
  ward: string,
  street: string,
): Promise<string | null> {
  const { data, error } = await supabase.rpc("find_office_for_address", {
    p_region: region,
    p_district: district,
    p_ward: ward,
    p_street: street,
  });
  if (error) {
    console.warn("[officeRegistry] find_office_for_address:", error.message);
    return null;
  }
  return (data as string) || null;
}

/**
 * Assign a citizen to an office based on their address.
 * P2-T9: called on profile completion.
 * P2-T11: called on address change (recalculates).
 * P2-T10: if no direct mtaa mapping found, falls back to ward office and
 *         alerts admin via notification.
 */
export async function assignOfficeForAddress(
  userId: string,
  region: string,
  district: string,
  ward: string,
  street: string,
): Promise<{ officeId: string | null; isFallback: boolean }> {
  if (!region || !district || !ward) return { officeId: null, isFallback: false };

  // Check if a direct mtaa office serves this street (for fallback detection)
  let isFallback = false;
  try {
    const { data: mtaaMatch } = await supabase
      .from(TABLE)
      .select("id")
      .eq("office_type", "mtaa")
      .eq("active", true)
      .eq("region", region)
      .eq("district", district)
      .eq("ward", ward)
      .or(`served_streets.cs.{${street}},mtaa.ilike.%${street}%`)
      .limit(1);
    isFallback = !mtaaMatch || mtaaMatch.length === 0;
  } catch {
    isFallback = true;
  }

  const officeId = await findOfficeForAddress(region, district, ward, street);

  if (officeId) {
    await supabase.from("users").update({ assigned_office_id: officeId }).eq("id", userId);

    // P2-T10: alert admin if we fell back to a non-mtaa office for an unmapped street
    if (isFallback && street) {
      try {
        const { data: admins } = await supabase
          .from("users")
          .select("id")
          .eq("role", "admin")
          .limit(5);
        for (const a of admins || []) {
          await supabase.from("notifications").insert({
            user_id: a.id,
            title: "Unmapped Street — Office Fallback",
            message: `Street "${street}" (${ward}, ${district}, ${region}) has no Mtaa office mapping. Citizen assigned to fallback office. Please map this street.`,
            type: "warning",
          });
        }
      } catch {
        /* notifications optional */
      }
    }
  }

  return { officeId, isFallback };
}
