apply plugin: 'com.android.application'

android {
    namespace "tz.go.e_serikali_mtaa"
    compileSdk 36
    defaultConfig {
        applicationId "tz.go.e_serikali_mtaa"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "androidx.webkit:webkit:1.12.1"
    implementation "androidx.core:core-splashscreen:1.0.1"
    implementation "com.google.android.material:material:1.12.0"
    implementation project(':capacitor-android')
    implementation project(':capacitor-app')
    implementation project(':capacitor-haptics')
    implementation project(':capacitor-status-bar')
    implementation project(':capacitor-splash-screen')
}
